name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Install Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node_version: 14.x
          
      # Install dependencies
      - name: Install dependencies
        run: yarn
      
      # Run build
      - name: Run build
        run: yarn build

      # Copy code to Digital Ocean
      - name: Copy code to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/app/gobarber-api"
      
      # Run production scripts
      - name: Run production scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/gobarber-api
            yarn 
            ./node_modules/.bin/typeorm migration:run
            pm2 restart gobarber-api
          
